# Generated by Django 4.0.5 on 2022-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apepat', models.CharField(max_length=30)),
                ('apemat', models.CharField(max_length=30)),
                ('edad', models.IntegerField(max_length=3)),
                ('nombre_vacuna', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
