# Generated by Django 4.0.5 on 2022-06-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
    ]
