# Generated by Django 4.0.5 on 2022-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorio', '0002_remove_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
